[package]
name = "fuzzer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fuzzer"
path = "src/main.rs"

[dependencies]
batch-channel = "0.4.2"
clap = { version = "4.5.29", features = ["derive"] }
